### ISSUE TITLE
SAXParseException if findbugsFailOnError := true only

### ISSUE THREAD

**Issue by olmaga** [josephearl/sbt-findbugs#6]
Hi (sorry for the early enter-hit)

I have the follwing settings using 2.4.0:

```
findbugsReportType := Some(FindBugsReportType.Html)

findbugsFailOnError := true

```

and get this stacktrace:

`org.xml.sax.SAXParseException; lineNumber: 80; columnNumber: 324; The content of elements must consist of well-formed character data or markup.
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
    at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.startOfMarkup(XMLDocumentFragmentScannerImpl.java:2636)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2734)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
    at scala.xml.factory.XMLLoader$class.loadXML(XMLLoader.scala:40)
    at scala.xml.XML$.loadXML(XML.scala:57)
    at scala.xml.factory.XMLLoader$class.loadFile(XMLLoader.scala:47)
    at scala.xml.XML$.loadFile(XML.scala:57)
    at uk.co.josephearl.sbt.findbugs.FindBugs$.uk$co$josephearl$sbt$findbugs$FindBugs$$processIssues(FindBugs.scala:52)
    at uk.co.josephearl.sbt.findbugs.FindBugs$$anonfun$1.apply(FindBugs.scala:40)
    at uk.co.josephearl.sbt.findbugs.FindBugs$$anonfun$1.apply(FindBugs.scala:40)
    at scala.Option.map(Option.scala:145)
    at uk.co.josephearl.sbt.findbugs.FindBugs$.findbugs(FindBugs.scala:40)
    at uk.co.josephearl.sbt.findbugs.FindBugsPlugin$autoImport$$anonfun$findbugsTask$1.apply(FindBugsPlugin.scala:81)
    at uk.co.josephearl.sbt.findbugs.FindBugsPlugin$autoImport$$anonfun$findbugsTask$1.apply(FindBugsPlugin.scala:74)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
`

weirdly it's only there if the findbugsFailOnError := true is set

**Comment by olmaga** [comment]
I just figured out that if I specify a priority it does not fail with Html but fails with FancyHtml

Additionally, this config works through - does not fail even if there are failures ^^

```
findbugsReportType := Some(FindBugsReportType.Html)

findbugsPriority := FindBugsPriority.Medium

findbugsReportPath := Some(target.value / "findbugs-report.html")

findbugsFailOnError := true
```

Edit: okay: it seems it just has random errors depending on what errors it finds :'-(

**Comment by josephearl** [comment]
@olmaga Thanks for the bug report!

It looks like this an issue when using `failOnError` in combination with the HTML report type. 

When `failOnError` is set the plugin attempts to parse the file to work out what errors are present. However this logic was designed for the XML report type and wasn't tested fully with HTML reports.

Can you send me one or more of the findbugs-report.html which cause issues?

**Comment by olmaga** [comment]
-file link removed-

**Comment by olmaga** [comment]
Btw: for me it shows success as return type when there are warnings found ... even though i'm on XML and findbugsFailOnError := true

**Comment by josephearl** [comment]
Thanks - do you have the XML file produced so I can look into that?

**Comment by olmaga** [comment]
i think it was this one

**Comment by olmaga** [comment]
I think it was this one:

-file link removed-

Could you delete the files again from the issue? => they contain my paths etc... would be nice

**Comment by josephearl** [comment]
@olmaga sure - links are now deleted, thanks for the files.

The way `findbugsFailOnError` is currently implemented it really only works with the Xml report type. I've raised #7 to look at improving this, for the mean time I will just have the plugin produce a useful error message and fail the build, and update the documentation to reflect this reality.

Will look into why your Xml file is not failing the build and update the plugin if needed.

**Comment by josephearl** [comment]
OK seems the issue with your Xml file is that some SourceLines did not contain a start and the plugin assumed they did, which caused it to bomb out.

**Comment by josephearl** [comment]
@olmaga please take a look at PR #8 and see if that fixes your issue with the XML report.

If you clone the branch `html-fail-on-error` you can use it by publishing it locally with `sbt publishLocal` and then using version `2.4.1-SNAPSHOT` in your project.

**Comment by josephearl** [comment]
I've merged in the PR, please try the latest release 2.4.1 and see if your issue is solved

**Comment by olmaga** [comment]
I see ;-)

> `findbugsFailOnError := true` can only be used in combination with `findbugsReportType := Some(FindBugsReportType.Xml)`

also for me this makes sence. I don't have the errors anymore I had before, but I don't have the exact same source-code anymore. Thanks for fixing this! Very nice

**Comment by etyurkin** [comment]
Invalid xml is produced by findbugs itself.
This is most likely caused by low memory. I had it recently, increasing findbugsMaxMemory didn't help but reboot did.
